#preload = ~/Pictures/wallpaper.jpg
preload = ~/Pictures/abisko.jpeg
preload = ~/Pictures/rose-pine-wallpaper.png

wallpaper = ,~/Pictures/rose-pine-wallpaper.png
#wallpaper = ,~/Pictures/abisko.jpeg
