[ids]
*

[global]
chord_timeout = 300

[main]
# Maps capslock to escape
capslock = overload(user-capslock, esc)

# Remaps the escape key to capslock
esc = capslock

# Makes home row keys usable as modifier keys
## Left side
a = overloadt(meta, a, 200)
#meta = a
s = overloadt(alt, s, 200)
#alt = s
d = overloadt(control, d, 200)
#control = d
f = overloadt(shift, f, 200)
#shift = f

## Right side
j = overloadt(shift, j, 200)
#shift = j
k = overloadt(control, k, 200)
#control = k
l = overloadt(altgr, l, 200)
#altgr = l
; = overloadt(meta, ;, 200)
#meta = ;

[user-capslock:G]
h = left
j = down
k = up
l = right
f = pagedown
b = pageup
x = backspace
d = delete
1 = leftmouse
2 = rightmouse
3 = middlemouse
g = home
esc = esc

[user-capslock+shift]
g = end
# vim: ft=toml
