[ColorScheme]
active_colors={fg}, {surface}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {surface}, {bg}, {bg}, {accent}, {bg}, {dim}, {accent}, {surface}, {bg}, {surface}, {fg}, {dim}
disabled_colors={fg}, {surface}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {surface}, {bg}, {bg}, {accent}, {bg}, {dim}, {accent}, {surface}, {bg}, {surface}, {fg}, {dim}
inactive_colors={fg}, {surface}, #ffffff, #cacaca, #9f9f9f, #b8b8b8, {fg}, #ffffff, {fg}, {surface}, {bg}, {bg}, {accent}, {bg}, {dim}, {accent}, {surface}, {bg}, {surface}, {fg}, {dim}
# vim: ft=ini
