source = ~/.config/hypr/colors.conf

background {
  monitor =
  path = screenshot

  blur_passes = 3
  blur_size = 4
}

input-field {
  monitor =
  size = 400, 30
  fail_text = <i>$FAIL <b>($ATTEMPTS attempt(s))</b></i>
  font_family = Adwaita Sans

  font_color = $bg
  outer_color = $surface
  inner_color = $fg
  check_color = $yellow
  fail_color = $red

  halign = center
  valign = center
}

# User label
label {
  monitor =
  text = Hello there, $USER
  color = $fg
  font_family = Adwaita Sans

  position = 0, 30
  halign = center
  valign = center

  shadow_passes = 1
  shadow_color = $bg
}

# Time label
label {
  monitor =
  text = $TIME
  color = $fg
  font_size = 25
  font_family = Adwaita Sans

  position = 0, 60
  halign = center
  valign = center

  shadow_passes = 1
  shadow_color = $bg
}

# Battery label
label {
  monitor =
  text = cmd[update:2000] printf "    "; cat /sys/class/power_supply/BAT0/capacity | tr -d "\n"; printf '%s' '%'
  font_size = 13
  font_family = Adwaita Sans
  color = $fg

  position = 5, 0
  halign = left
  valign = top

  shadow_passes = 1
  shadow_color = $bg
}

# Keyboard label
label {
  monitor =
  text =  $LAYOUT
  font_size = 13
  font_family = Adwaita Sans
  color = $fg

  halign = left
  valign = top
  position = 90, 0

  shadow_passes = 1
  shadow_color = $bg
}
# vim: ft=hyprlang
