source = ~/.config/hypr/rose-pine.conf

background {
  monitor =
  path = $HOME/Pictures/rose-pine-wallpaper.png
}

input-field {
  monitor =
  size = 300, 20
  dots_size = 0.5

  position = 0, -20
  halign = center
  valign = center
}

# User label
label {
  monitor =
  text = Hello there, $USER
  color = $text
  font_family = Cantarell

  position = 0, 10
  halign = center
  valign = center

  shadow_passes = 1
  shadow_color = $base
}

# Time label
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 25
  font_family = Cantarell

  position = 0, 40
  halign = center
  valign = center

  shadow_passes = 1
  shadow_color = $base
}
