source = ~/.config/hypr/rose-pine.conf

background {
  monitor =
  path = $HOME/Pictures/rose-pine-wallpaper.png
}

input-field {
  monitor =
  size = 300, 20
  dots_size = 0.5

  position = 0, -20
  halign = center
  valign = center
}

label {
  monitor =
  text = Hello there, $USER
  color = $text
  font_family = Cantarell

  position = 0, 80
  halign = center
  valign = center
}
