colorscheme gruvbox-dark
add-highlighter global/ number-lines -relative -separator "   " -hlcursor
add-highlighter global/ show-matching

set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 8,3
